version: '3.8'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/api.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/api.env
    ports:
      - 5436:5432

volumes:
    postgres_data:








# version: '3.8'

# services:
#   server:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     volumes:
#       - ./backend/:/backend/
#     command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
#     env_file:
#       - ./backend/api.env
#     ports:
#       - 8001:8000
#     depends_on:
#       - db

#   db:
#     container_name: postgres_container
#     image: postgres:13-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_DB: postgres
#       PGDATA: /var/lib/postgresql/data/
#     ports:
#       - 5436:5432
  
#   pgadmin:
#     container_name: pgadmin_container
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#       PGADMIN_CONFIG_SERVER_MODE: 'False'
#     volumes:
#        - pgadmin:/var/lib/pgadmin
#     ports:
#       - "${PGADMIN_PORT:-5050}:80"

# volumes:
#     postgres_data:
#     pgadmin:
